#!/bin/bash

# Ensure the script is run with root privileges
if [ "$(id -u)" -ne 0 ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

# Initialize brightness level variable
BRIGHTNESS_LEVEL=0

# Prompt user for input until a valid value is received
while [ $BRIGHTNESS_LEVEL -lt 1 ] || [ $BRIGHTNESS_LEVEL -gt 255 ]; do
  echo -n "Enter a brightness level (1-255): "
  read BRIGHTNESS_LEVEL
  # Check if input is an integer
  if ! [[ "$BRIGHTNESS_LEVEL" =~ ^[0-9]+$ ]]; then
    echo "Please enter a valid integer."
    BRIGHTNESS_LEVEL=0 # Reset to invalid value to continue the loop
  elif [ $BRIGHTNESS_LEVEL -lt 1 ] || [ $BRIGHTNESS_LEVEL -gt 255 ]; then
    echo "The value must be between 1 and 255."
  fi
done

# Path to the brightness file
BRIGHTNESS_FILE="/sys/class/backlight/amdgpu_bl1/brightness"

# Change the brightness
echo $BRIGHTNESS_LEVEL | sudo tee $BRIGHTNESS_FILE > /dev/null

echo "Brightness set to $BRIGHTNESS_LEVEL"
